input = """
1. AASTHA RAJKUMAR DONGARE
2. ABHAY ANIL DHOTKAR
3. ABHISHEK SHYAMSUNDER BA
4. ADITYA SUNIL DESHMUKH
5. AKANKSH ASHISH BODAKHE
6. AMIT SIDDHESHWAR SURYAW
7. ANMOL AMIT MORAY
8. ATHARVA DULESHWAR SHRIK
9. AASHISH PRAKASHCHANDRA
10. AYUSH RAVINDRA SHAHU
11. AYUSH VINOD MAHALLE
12. BHAVIK THOOL YASHASVI
13. CHETNA RAVINDARAO SALVE
14. DEVANSH SHRINIVASAN PARA
15. DHIRAJ GAJANAN SAHARE
16. DHIRAJ GULAB CHAUDHARI
17. DUSHYANT RAJENDRA CHAM
18. ESHA CHANDRASHEKHAR RAN
19. GAYATRI PRASHANT DESHKA
20. HEMANT AKRE
21. JAY SUBHASH BELE
22. KARN DEEPAK GUPTA
23. KASHMINI ANIL MESHRAM
24. KAUSTUBH DNYANDEO WARA
25. KAYNAT FIRDOS SHEIKH
26. KINJAL DEEPAK TIWARI
27. KUNAL KRUSHNA WASNIK
28. KUNAL PUNESH RAHANGDALE
29. KUNAL PURANLAL THAKRE
30. KUSHALL RAJESH SHARMA
31. LALIT KAMLAKAR GHATOLE
32. MAITREYA SANJAY SALODKAR
33. MANJIRI DINESH DANGRE
34. MAQSOOD OZAHIR
35. MARUFA ASGARALI MANSURI
36. MRUDULA SANJAY WANKAR
37. NIDHISH SANJEEV WAGHMAR
38. NIHAL SHIOCHARAN GAIKWA
39. NIKHIL VINOD WAYZODE
40. NISARGA CHATURDAS TELAN
41. PIYUSH SANTOSH DOIFODE
42. PRANAV MANOJ TRIPATHI
43. PRANOTI MAHESH GULHANE
44. PRASAD SANJAY JOSHI
45. PRATHAM VIRENDRA PENDAM
46. PRATIK PRADEEP BAGDI
47. PRATHYUSH JAYANT SAKHARK
48. PRIYA RUMACHAND NANDANW
49. PRIYANKA RAMESH TALOKAR
50. PRIYANSHU GANATRA
51. RAFIQ MOHD
52. ROHINI HARIDAS SHAMBHAR
53. RUSHIKESH GHAWGHAWE
54. SAHIL DEVANAND MARBATE
55. SAHIL RAJESH KUHIKAR
56. SAHIL RAJESH RATHOD
57. SAKHI VIJAYRAO CHOUDHAR
58. SAKINA ALI
59. SAKSHI ANIL NIMJE
60. SAPNA SANTOSHRAO JOSHI
61. SARTHAK PRABHAKAR KADU
62. SHRADDHA SANJAY GIRI
63. SHIVAM SAMBAJI MOREY
64. SHUBHLAK RAVISHANKAR KA
65. SUJATA DHARMDAS RANDHAY
66. SUNIL GHASIRAM DEWANGA
67. SUSHIL MIHEERA JADHAV
68. SWARALI SUNIL PRAYAGI
69. TEJAS GAUTAM TITARE
70. TEJASWINI ANIL MANKAR
71. UTKARSH SATISH GONDE
72. VEDANT KAILASH RATHOD
73. VEDANT SANJAY SARATE
74. VEDANTI DASHRATH DHOLE
75. VEDIKA SUBHASH RAUT
76. VINAMRA KISHOR PALANDUR
77. VISHAKHA DIWAKAR KURZEK
"""

phase1 = ""

for line in input.split("\n"):
    if line:
        phase1 += line.split(".")[1].strip() + "\n"

for i, line in enumerate(sorted(phase1.split("\n"))):
    if line:
        print(i, line)